C300/Models/Thread.cs
using System;
using System.Collections.Generic;

namespace C300.Models
{
    public partial class Thread
    {
        public Thread()
        {
            Comment = new HashSet<Comment>();
        }

        public int ThreadId { get; set; }
        public string ThreadName { get; set; }
        public string ThreadDescription { get; set; }
        public DateTime CreatedDate { get; set; }
        public int TopicId { get; set; }
        public int UserId { get; set; }
        public int? CommentCount { get; set; }
        public int? Like { get; set; }

        public virtual ICollection<Comment> Comment { get; set; }
    }
}

C300/Controllers/ThreadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using C300.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Data.Common;
using System.Data.SqlClient;
using System.Security.Claims;
using System.Security.Principal;

namespace C300.Controllers
{
    public class ThreadController : Controller
    {
        private AppDbContext _dbContext;
        private IHttpContextAccessor _contextAccessor;

        private HttpContext _context { get { return _contextAccessor.HttpContext; } }

        public ThreadController(AppDbContext dbContext, IHttpContextAccessor contextAccessor)
        {
            _dbContext = dbContext;
            _contextAccessor = contextAccessor;
        }

        public string userEmail
        {
            get
            {

                var userEmail = "SystemGenerated - Guest";
                if (_context != null)
                {
                    if (_context.User != null)
                    {
                        var identity = _context.User.Identity;
                        if (identity != null && identity.IsAuthenticated)
                        {
                            userEmail = identity.Name;
                        }
                    }
                }
                return userEmail;
            }
        }

        private void BacklogActivity(string action)
        {
            if (User.Identity.IsAuthenticated)
            {
                var backlog = new Backlog()
                {
                    Name = userEmail,
                    Action = action,
                    Datetime = DateTime.Now,
                    UserId = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value)
                };

                _dbContext.Backlog.Add(backlog);

                _dbContext.SaveChanges();
            }
            else
            {
                var backlog = new Backlog()
                {
                    Name = "System Generated Guest",
                    Action = action,
                    Datetime = DateTime.Now,
                    UserId = 0
                };

                _dbContext.Backlog.Add(backlog);

                _dbContext.SaveChanges();
            }
        }

        private void PreparePreference()
        {
            if (User.Identity.IsAuthenticated)
            {
                DbSet<Preference> dbs1 = _dbContext.Preference;
                int userId = 0;
                Int32.TryParse(HttpContext.User.FindFirst(ClaimTypes.Sid).Value, out userId);
                Preference model1 = dbs1.Where(p => p.UserId == userId).FirstOrDefault();
                ViewData["preference"] = model1;
            }
            else
            {
                ViewData["preference"] = new Preference();
            }
        }

        [Authorize]
        public IActionResult Index(int id)
        {
            BacklogActivity("Accessed Forum Page");
            PreparePreference();
            DbSet<Thread> dbs = _dbContext.Thread;
            DbSet<Comment> dbs3 = _dbContext.Comment;
            DbSet<Emsuser> dbs4 = _dbContext.Emsuser;
            List<Thread> threadlist = dbs.Where(o => o.TopicId == id).ToList();
            DbSet<Topic> dbs2 = _dbContext.Topic;
            var name = new List<string>();
            var model2 = dbs.Select(o => o.UserId).ToList();
            foreach (var i in model2)
            {
                name.Add(dbs4.Where(o => o.UserId == i).Select(o => o.Name).SingleOrDefault());
            }
            ViewData["name"] = name;

            var comment = dbs3.Count();

            foreach (var item in dbs3.Select(o => o.ThreadId).ToList())
            {
                List<Comment> count = dbs3.Where(o => o.ThreadId == item).ToList();
                int c = count.Count();
                ViewData["Count"] = c;

            }



            ViewData["id"] = id;

            return View(threadlist);
        }

        public IActionResult Comment()
        {

            PreparePreference();
            return View();
        }
        public IActionResult Likes(int x)
        {
            PreparePreference();
            DbSet<Thread> likes = _dbContext.Thread;
            Thread threadlike = likes.Where(o => o.ThreadId == x).FirstOrDefault();
            threadlike.Like = threadlike.Like + 1;
            if (_dbContext.SaveChanges() == 1)
            {
                BacklogActivity("Liked a Thread");
                TempData["Msg"] = "Liked!";
            }
            else
                TempData["Msg"] = "Error Liking!";

            return RedirectToAction("Index", new { id = threadlike.TopicId });
        }
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            PreparePreference();
            ViewData["CategoryID"] = TempData["Category"];
            DbSet<Topic> dbs = _dbContext.Topic;
            List<Topic> topicList = dbs.ToList();
            ViewData["topic"] = topicList;
            return View();
        }
        [HttpPost]
        [Authorize]
        public IActionResult Create(Thread thread)
        {
            PreparePreference();
            if (ModelState.IsValid)
            {
                DbSet<Topic> dbs3 = _dbContext.Topic;
                Topic topic = dbs3.Where(o => o.TopicId == thread.TopicId).FirstOrDefault();
                DbSet<Thread> dbs = _dbContext.Thread;
                DbSet<Comment> dbs1 = _dbContext.Comment;
                thread.CommentCount = 1;
                thread.CreatedDate = DateTime.Now;
                thread.UserId = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value);


                dbs.Add(thread);
                topic.ThreadCount = topic.ThreadCount + 1;
                dbs3.Update(topic);

                if (_dbContext.SaveChanges() == 1)
                {
                    BacklogActivity("Created a New Thread");
                    TempData["Msg"] = "NEW THREAD ADDED";

                }
                else
                {
                    TempData["Msg"] = "NEW THREAD ADDED";
                }
            }
            else
            {
                TempData["Msg"] = "Invalid Information";

            }
            return RedirectToAction("Index", new { id = thread.TopicId });

        }
        public IActionResult Delete(int id)
        {
            PreparePreference();
            DbSet<Comment> dbs = _dbContext.Comment;
            DbSet<Topic> dbs3 = _dbContext.Topic;
            DbSet<Thread> dbs2 = _dbContext.Thread;

            Thread del = dbs2.Where(o => o.ThreadId == id).FirstOrDefault();
            var topicid = del.TopicId;
            var count = dbs.Where(o => o.ThreadId == id).Count();

            if (del != null)
            {
                if (count == 0)
                {
                    Topic topic = dbs3.Where(o => o.TopicId == topicid).FirstOrDefault();
                    topic.ThreadCount = topic.ThreadCount - 1;
                    dbs2.Remove(del);
                    if (_dbContext.SaveChanges() == 1)
                    {
                        BacklogActivity("Deleted a Thread");
                        TempData["Msg"] = "Thread Deleted";
                    }
                    else
                        TempData["Msg"] = "Thread deleted";
                }
                else
                {
                    TempData["Msg"] = "Thread is Not Empty";
                }
            }
            return RedirectToAction("Index", new { id = del.TopicId });

        }

    }
}

C300/Views/Thread/Create.cshtml
@model Thread

@{
    ViewData["Title"] = "Create Thread";
    List<Topic> topicList = ViewData["topic"] as List<Topic>;
    var id = ViewData["id"];

}
@*<style>
        html {
      font: 300 100%/1.5 Ubuntu, sans-serif;
      color: #333;
      overflow-x: hidden;
    }
    h2 {
      margin: 0;
      color: #8495a5;
      font-size: 2.5em;
      font-weight: 300;
    }
    #contact-form {
      max-width: 1208px;
      max-width: 75.5rem;
      margin: 0 auto;
    }
    #contact, label, input[name="submit"] {
      position: relative;
    }
    label > span, input, textarea, button {
      box-sizing: border-box;
    }
    label {
      display: block;
    }
    label > span {
      display: none;
    }
    input, textarea, button {
      width: 100%;
      padding: 0.5em;
      border: none;
      font: 300 100%/1.2 Ubuntu, sans-serif;
    }
    input[type="text"], input[type="email"], textarea {
      margin: 0 0 1em;
      border: 1px solid #ccc;
      outline: none;
    }
    input.invalid, textarea.invalid {
      border-color: #d5144d;
    }
    textarea {
      height: 6em;
    }
    input[type="submit"], button {
      background: #a7cd80;
      color: #333;
    }
    input[type="submit"]:hover, button:hover {
      background: #91b36f;
    }

      label > span {
        vertical-align: top;
        display: inline-block;
        width: 26.3736%;
        padding: 0.5em;
        border: 1px solid transparent;
        text-align: right;
      }
      input, textarea, button {
        width: 73.6263%;
        line-height: 1.5;
      }
      textarea {
        height: 10em;
      }
      input[type="submit"], button {
        margin-left: 26.3736%;
      }
    }

      #contact-form:after {
        content: '';
        display: inline-block;
        width: 100%;
      }
      #contact-form h2 {
        margin-left: 17.2661%;
      }
      #contact-form form, #contact-form aside {
        vertical-align: top;
        display: inline-block;
        width: 65.4676%;
        text-align: left;
        line-height: 1.5;
      }
      #contact-form aside {
        width: 30.9353%;
      }
    }
    </style>
    <h2>New Thread</h2>
    <section id="contact-form">
        <form id="contact" name="contact" accept-charset="utf-8">
            <label><span>User Id</span><input name="user id" asp-for=UserId placeholder="Email" /></label>
            <label><span>Category</span><input name="name" asp-for="ThreadName" type="text" placeholder="Category" /></label>


            <input name="submit" type="submit" value="Send" />
        </form>

    </section>*@
<div class="container">
    <form asp-action="Create" method="post" asp-controller="Thread">
        <h3>New Thread  </h3>

        <input type="text" asp-for="ThreadName" placeholder="Thread Name" />
        <span asp-validation-for="ThreadName" class="text-danger"></span>


        <select asp-for="TopicId">
            @foreach (Topic item in topicList)
            {

                <option value="@item.TopicId"> @item.TopicName</option>


            }

        </select>
<textarea asp-for="ThreadDescription" rows="5" placeholder="Description"></textarea>

        <span asp-validation-for="ThreadDescription" class="text-danger"></span>


        <button type="submit" asp-route-id="@id">Create!</button>
    </form>
</div>

<style>
    * {
        box-sizing: border-box;
    }


    body {
        font-family: 'Economica', 'Arial', sans-serif;
        font-size: 18px;
    }

    .container {
        position: relative;
        width: 100%;
        height: 70%;
        margin: 0 auto;
    }

    form {
        position: relative;
        width: 100%;
        margin: 50px auto;
        max-height: 900px;
        max-width: 700px;
        border-radius: 20px;
        padding: 50px;
        margin-left: 250px;
        background-color: #6AA84F;
        text-align: center;
    }

    input, textarea {
        display: inline-block;
        width: 100%;
        margin: 20px 0;
        padding: 10px;
        border: 2px dashed lightblue;
        outline: none;
        font-size: 20px;
        font-family: 'Economica', 'Arial', sans-serif;
        font-weight: 400;
        transition: all 0.2s ease;
    }

        input:focus {
            border-color: deepskyblue;
        }

    button {
        position: absolute;
        left: calc(50% - 150px / 2);
        bottom: calc(- 50px / 2);
        width: 150px;
        height: 50px;
        padding: 10px 15px;
        margin-top: 20px;
        border: none;
        outline: none;
        cursor: pointer;
        color: white;
        font-family: 'Economica', 'Arial', sans-serif;
        font-size: 20px;
        font-weight: 700;
        background: mediumblue;
        transition: all 0.2s ease;
    }

        button:hover {
            background: midnightblue;
        }

        button.valid,
        button.valid:hover {
            background: mediumseagreen;
        }









    @@keyframes drawBorder {
        from {
            stroke-dasharray: 4000;
            stroke-dashoffset: 4000;
        }

        to {
            stroke-dasharray: 4000;
            stroke-dashoffset: 0;
        }
    }

    h3 {
        margin-top: 0;
        margin-bottom: 20px;
        text-transform: uppercase;
        font-size: 24px;
        font-weight: 700;
    }
</style>

C300/Views/Thread/Index.cshtml
@model List<Thread>

@{
    ViewData["Title"] = "Thread";
    Layout = "~/Views/Shared/_Layout.cshtml";

    List<string> name = ViewData["name"] as List<string>;

}

<script>

    $(window).scroll(function () {
        var width = $(window).width();
        if (width < 800) {
            $('#scroll').hide();
        } else {
            var e = $(window).scrollTop();
            e > 150 ? $('#scroll').fadeIn() : $('#scroll').fadeOut();
        }

    });

</script>

<style>
    body {
        font-family: 'Open Sans', sans-serif;
        width: 100%;
    }

    header {
        margin: 0;
        border-bottom: 3px solid hsl(195, 73%, 58%);
    }

    a {
        display: inline-block;
        color: inherit;
        text-decoration: none;
    }

    .row.mt {
        margin-top: 1.25em;
        margin-top:5%;
    }

    .row.mb {
        margin-bottom: 1.25em;
    }

    .pad {
        padding: 15px;
    }

    .spad {
        padding: 5px;
    }

    .lpad {
        padding: 20px;
    }

    .ar {
        text-align: right;
    }

    .logo {
        color: #ffffff;
        font-size: 18px;
        text-transform: lowercase;
    }

        .logo span:first-child {
            font-weight: 400;
        }

        .logo span:last-child {
            color: #b3b3b3;
            font-weight: 300;
        }

    nav.menu a {
        margin: 0 7px;
        color: #b3b3b3;
        font-size: 12px;
        font-weight: 600;
        text-decoration: none;
    }

        nav.menu a:last-child {
            margin: 7px 0 7px 7px;
        }

        nav.menu a.current {
            color: #ffffff;
        }

    .top-msg {
        border-bottom: 5px solid;
        color: #666666;
        font-size: 13px;
        font-weight: 300;
    }

    /*.breadcrumb a {
        transition: color .5s;
    }

        .breadcrumb a:hover {
            color: #333333;
        }

        .breadcrumb a:after {
            content: '\00a0\00a0\002F\00a0\00a0';
            color: #b3b3b3;
        }

        .breadcrumb a:last-child:after {
            content: '\00a0\00a0\002F\00a0\00a0 now you\0027re here';
            color: #b3b3b3;
        }*/

    a.primary {
        color: #b3b3b3;
        transition: color .5s;
    }

        a.primary:hover {
            color: #46bbe2;
        }

    a.underline {
        color: #b3b3b3;
    }

        a.underline:hover:after {
            content: '';
            display: block;
            width: inherit;
            height: 2px;
            background-color: #46bbe2;
            margin-bottom: -2px;
            animation: link .9s ease;
        }

    @@keyframes link {
        from {
            width: 0;
        }

        to {
            width: 100%;
        }
    }
    /* Topic */
    .rounded {
        overflow: hidden;
    }

        .rounded.top {
            border-radius: 4px 4px 0 0;
        }

        .rounded.all {
            border-radius: 4px;
        }

    .forum-category {
        background-color: #6B8E23;
        color: #ffffff;
        font-weight: 600;
        font-size: 20px;
    }

    .forum-head > .column {
        background-color: #696969;
        border-right: 1px;
        border-left: 1px;
        color: #ffffff;
        font-weight: 300;
        font-size: 18px;
        text-align: center;
    }

        .forum-head > .column:first-child {
            text-align: left;
            border-left: none;
        }

        .forum-head > .column:last-child {
            border-right: none;
        }

    .forum-topic > .column {
        min-height: 71px;
        max-height: 71px;
        background-color: #f5f5f5;
        border-bottom: 1px;
        color: #808080;
        font-size: 14px;
    }

        .forum-topic > .column:first-child {
            color: #999999;
            font-size: 30px;
            text-align: center;
        }

        .forum-topic > .column:nth-child(n+3) {
            text-align: center;
        }

        .forum-topic > .column:last-child {
            text-align: left;
        }

    .forum-topic a {
        transition: color .5s;
        color: #1fa8d6;
        font-weight: 600;
    }

        .forum-topic a:hover {
            color: #21a7d4;
        }

    .forum-topic span {
        display: block;
        margin: 0 0 2px 0;
    }

    .overflow-control {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .forum-topic .column:nth-child(2) span.overflow-control {
        width: 70%;
        height: 15px;
    }

    .forum-topic span.center {
        padding-top: 10px;
    }

    .normal {
        background-color: #f5f5f5;
        color: #808080;
        font-size: 12px;
    }

        .normal h1.inset {
            background-color: #16232d;
            margin: -20px -20px 20px -20px;
            color: #ffffff;
            padding: 15px 20px 15px 20px;
            font-size: 12px;
            font-weight: 300;
        }

        .normal p {
            margin: 0 0 40px 0;
            line-height: 20px;
        }

            .normal p:last-child {
                margin: 0;
            }

    #scroll {
        display: none;
        width: 27px;
        background-color: #16232d;
        position: fixed;
        right: 60px;
        bottom: 20px;
        border-radius: 3px;
        cursor: pointer;
        padding: 5px;
        text-align: center;
        color: #ffffff;
    }

        #scroll.show {
            display: block;
        }

    @@media only screen and (max-width: 768px) {
        header {
        }

        .logo,
        nav {
            text-align: center;
        }

            nav.menu a {
                margin: 7px;
            }

        .fa-star {
            background-color: gold;
        }


        .forum-head > .column {
            color: #ffffff;
            border: none;
            font-weight: 600;
        }

        .rounded,
        .rounded.top,
        .rounded.all {
            border-radius: 0;
        }

        .overflow-control > a,
        .overflow-control {
            display: block;
            width: 290px;
            white-space: nowrap;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    }
</style>

<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
<span style="color:red;">@TempData["Msg"]</span><br />
<form>
    <a href="#top" id="scroll">
        <i class="icon-angle-up"></i>
    </a>

    <p>

        <a asp-action="Create" id="thread" style="background-color:lightgreen;margin-left:80%;font-weight:500;font:bolder" asp-controller="Thread" class="btn btn-default pull-left"><i class="fa fa-edit"></i> Create Thread</a>
    </p>
    <br />
    <br />
    <div class="row mt">
        <div class="large-12">
            <div class="large-12 forum-category rounded top">
                <div class="large-8 small-10 column lpad">
                    <!--Display topic being selected-->
                    Threads in Topic:
                </div>
                <div class="large-4 small-2 column lpad ar ">

                </div>
            </div>

            <div class="toggleview">
                <div class="large-12 forum-head">
                    <div class="large-8 small-8 column lpad">
                        Thread
                    </div>
                    <div class="large-2 small-4 column lpad">
                        Replies
                    </div>
                    <div class="large-2 small-4 column lpad">
                        Action
                    </div>
                </div>
                @if (Model != null)
                {
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <div class="large-12 forum-topic">
                            <div class="large-1 column lpad">
                                <span class="fa fa-star"></span>
                            </div>
                            <div class="large-7 small-8 column lpad">
                                <span class="overflow-control">

                                    <a asp-action="Index" asp-controller="Comment" asp-route-id="@Model[i].ThreadId">@Model[i].ThreadName</a>
                                </span>
                                <span class="overflow-control">
                                    @Model[i].ThreadDescription
                                </span>
                            </div>

                            <div class="large-2 column lpad">
                                <span class="center">@Model[i].CommentCount</span>
                            </div>
                            <div class="large-2 small-4 column pad">
                                @if (User.IsInRole("Admin"))
                                {
                                    <a asp-action="Delete" asp-controller="Thread" style="color:red;float:right;height:10px" asp-route-id="@Model[i].ThreadId">&Chi;</a>
                                }

                                <span style="color:deepskyblue;font:bolder">

                                    @name[i]
                                </span>

                                <span>
                                    @Model[i].CreatedDate 

                                <a asp-action="Likes" asp-controller="Thread" asp-route-x="@Model[i].ThreadId"><i class="fa fa-thumbs-up" style="font-size:20px"></i></a> &nbsp;
                                <b> Likes- @Model[i].Like @*<i class="fa fa-heart" style="font-size:10px;color:red"></i>*@</b>
                            </span>


                        </div>

                    </div>

                    }

                }

            </div>
        </div>
    </div>
    <div class="row mt mb" style="height:50px">
        <div class="large-12">
            <div class="large-12 small-12 forum-category rounded top lpad">
                <span></span>
            </div>

        </div>
    </div>
</form>