C300/Models/Emsuser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace C300.Models
{
    public partial class Emsuser
    {
        public Emsuser()
        {
            Comment = new HashSet<Comment>();
            Topic = new HashSet<Topic>();
        }

        public int UserId { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Name cannot be empty!")]
        public string Name { get; set; }

        public string Role { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Password cannot be empty!")]
        [DataType(DataType.Password)]
        //[RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*\W)\S{8,15}$", ErrorMessage = "Invalid password format")]
        public string Password { get; set; }

        [NotMapped]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm password and password do not match!")]
        public string ConfirmPassword { get; set; }


        public string Picture { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Date of birth cannot be empty!")]
        [DataType(DataType.Date)]
        public DateTime Dob { get; set; }

        //[Required(AllowEmptyStrings = false, ErrorMessage = "Country cannot be empty!")]
        public string Country { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Email cannot be empty!")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid Email Address!")]
        public string Email { get; set; }
        public Guid? ActivationCode { get; set; }
        public bool IsVerified { get; set; }
        public string ResetPasswordCode { get; set; }
        public string Status { get; set; }
        public int? Phone { get; set; }
        public string UpdatedBy { get; set; }

        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Topic> Topic { get; set; }
    }
}

C300/Controllers/EmsuserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using C300.Models;
using System.Dynamic;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using GemBox.Spreadsheet;
using System.IO;
using System.Data.Common;
using System.Data.SqlClient;
using System.Security.Claims;
using System.Text;
using System.Web;
using LINQtoCSV;
using System.Net.Mail;
using C300.Models;

namespace C300.Controllers
{
    public class EmsuserController : Controller
    {

        private AppDbContext _dbContext;
        private IHostingEnvironment _env;
        private readonly IList<Emsuser> data;
        private IHttpContextAccessor _contextAccessor;
        private HttpContext _context { get { return _contextAccessor.HttpContext; } }

        public EmsuserController(AppDbContext dbContext, IHostingEnvironment environment, IHttpContextAccessor contextAccessor)
        {
            _dbContext = dbContext;
            _env = environment;
            _contextAccessor = contextAccessor;
        }

        public string userEmail
        {
            get
            {

                var userEmail = "SystemGenerated - Guest";
                if (_context != null)
                {
                    if (_context.User != null)
                    {
                        var identity = _context.User.Identity;
                        if (identity != null && identity.IsAuthenticated)
                        {
                            userEmail = identity.Name;
                        }
                    }
                }
                return userEmail;
            }
        }

        private void BacklogActivity(string action)
        {
            if (User.Identity.IsAuthenticated)
            {
                var backlog = new Backlog()
                {
                    Name = userEmail,
                    Action = action,
                    Datetime = DateTime.Now,
                    UserId = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value)
                };

                _dbContext.Backlog.Add(backlog);

                _dbContext.SaveChanges();
            }
            else
            {
                var backlog = new Backlog()
                {
                    Name = "SystemGenerated - Guest",
                    Action = action,
                    Datetime = DateTime.Now,
                    UserId = 0
                };

                _dbContext.Backlog.Add(backlog);

                _dbContext.SaveChanges();
            }
        }

        private void PreparePreference()
        {
            if (User.Identity.IsAuthenticated)
            {
                DbSet<Preference> dbs1 = _dbContext.Preference;
                int userId = 0;
                Int32.TryParse(HttpContext.User.FindFirst(ClaimTypes.Sid).Value, out userId);
                Preference model1 = dbs1.Where(p => p.UserId == userId).FirstOrDefault();
                ViewData["preference"] = model1;
            }
            else
            {
                ViewData["preference"] = new Preference();
            }
        }

        public IActionResult Index()
        {
            BacklogActivity("Accessed View Users Page");
            PreparePreference();
            DbSet<Emsuser> dbs = _dbContext.Emsuser;
            List<Emsuser> model = dbs.OrderBy(p => p.UserId)
                                    .ToList();

            return View(model);

        }
        public IActionResult EmsuserInfo(int id)
        {
            PreparePreference();
            DbSet<Emsuser> dbs = _dbContext.Emsuser;
            List<Emsuser> EmsInfo = dbs.Where(o => o.UserId == id).ToList();
            return View(EmsInfo);
        }

        public IActionResult ViewUsers()
        {
            BacklogActivity("Accessed View Users Page");
            PreparePreference();
            DbSet<Emsuser> dbs = _dbContext.Emsuser;
            List<Emsuser> model = dbs.OrderBy(p => p.UserId)
                                    .ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult Deactivate(int id)
        {
            BacklogActivity("Deactivated User");
            PreparePreference();
            DbSet<Emsuser> dbs = _dbContext.Emsuser;
            Emsuser user = dbs.Where(o => o.UserId == id).FirstOrDefault();
            user.Status = "Inactive";
            user.Password = CreatePassword(8);
            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
        public IActionResult Activate(int id)
        {
            BacklogActivity("Activated User");
            PreparePreference();
            DbSet<Emsuser> dbs = _dbContext.Emsuser;
            Emsuser user = dbs.Where(o => o.UserId == id).FirstOrDefault();
            user.Status = "Active";
            user.Password = CreatePassword(8);
            _dbContext.SaveChanges();
            //SendVerificationLinkEmail(user.Email, "You are now Active in the system and Password is- " + user.Password); // Service ended
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AddUser()
        {
            //DbSet<Emsuser> dbs = _dbContext.Emsuser;
            //var adduser =
            //    dbs.ToList<Emsuser>()
            //       .OrderBy(p => p.Name)
            //       .Select(
            //           p =>
            //           {
            //               dynamic d = new ExpandoObject();
            //               d.value = p.UserId;
            //               d.text = p.Name;
            //               return d;
            //           }
            //       )
            //       .ToList<dynamic>();
            //ViewData["userform"] = adduser;
            PreparePreference();
            return View();
        }
        [HttpPost]

        public IActionResult AddUser(Emsuser emsuser)
        {
            PreparePreference();
            if (!ModelState.IsValid)
            {
                TempData["Msg"] = "Invalid data. Please check the input.";
                return RedirectToAction("Index");
            }
            try
            {
                DbSet<Emsuser> dbs = _dbContext.Emsuser;
                emsuser.IsVerified = true;

                if (HttpContext.Request.Form.Files != null)
                {
                    var files = HttpContext.Request.Form.Files;

                    string base64string = string.Empty;
                    foreach (var file in files)
                    {
                        if (file.Length > 0)
                        {
                            using (var ms = new MemoryStream())
                            {
                                file.CopyTo(ms);
                                var fileBytes = ms.ToArray();
                                base64string = Convert.ToBase64String(fileBytes);
                            }
                        }
                    }

                    emsuser.Picture = base64string;
                    emsuser.Status = "Active";
                    dbs.Add(emsuser);
                }
                if (_dbContext.SaveChanges() > 0)
                {
                    BacklogActivity("Added New User");
                    TempData["Msg"] = "New user added!";
                    // Add default Preference for new user
                    var newPreference = new Preference
                    {
                        UserId = emsuser.UserId,
                        HighestTemp = 0,
                        TempNoti = 0,
                        HighestHumidity = 0,
                        HumNoti = 0,
                        HighestLight = 0,
                        LightNoti = 0,
                        HighestWeight = 0,
                        WeightNoti = 0
                    };

                    _dbContext.Preference.Add(newPreference);
                    _dbContext.SaveChanges();

                    BacklogActivity("Added New User with default preference");
                }

                else
                { 
                    TempData["Msg"] = "Failed to update database!";

                }
              
                return RedirectToAction("Index");
            }

            catch (Exception)
            {
                throw;
            }

        }



        [HttpGet]
        public IActionResult Update(int id)
        {
            PreparePreference();
            DbSet<Emsuser> dbs = _dbContext.Emsuser;
            Emsuser tuser = dbs.Where(p => p.UserId == id)
                                      .FirstOrDefault();

            //if (tuser == null)
            //{

            return View(tuser);
            //}
            //else
            //{
            //    TempData["Msg"] = "Ems User not found!";

            //    return RedirectToAction("Index");
            //}

        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Update(Emsuser emsuser,
                                  IFormFile photo)
        {

            PreparePreference();
            DbSet<Emsuser> dbs = _dbContext.Emsuser;
            Emsuser tuser = dbs.Where(p => p.UserId == emsuser.UserId)
                                      .FirstOrDefault();
            var id = Convert.ToInt32(User.FindFirst(ClaimTypes.Sid).Value);
            var name = dbs.Where(o => o.UserId == id).Select(o => o.Name).FirstOrDefault();
            if (HttpContext.Request.Form.Files != null)
            {
                var files = HttpContext.Request.Form.Files;

                string base64string = string.Empty;
                foreach (var file in files)
                {
                    if (file.Length > 0)
                    {
                        using (var ms = new MemoryStream())
                        {

C300/Views/Emsuser/EmsuserInfo.cshtml
@model List<Emsuser>
    @{
        Layout = null;
    }

    <h4 style="text-align:center;border-bottom:1px solid #808080">EMSuser Information</h4>
    <div class="container">
        @foreach (var item in Model)
        {
            <p><label style="color:limegreen;font-size:18px;">Name:</label>@item.Name</p>
            <p><label style="color:limegreen;font-size:18px;">Role:</label>@item.Role</p>
            <p><label style="color:limegreen;font-size:18px;">Email:</label>@item.Email</p>
            <p><label style="color:limegreen;font-size:18px;">Country:</label>@item.Country</p>
            <p><label style="color:limegreen;font-size:18px;">DOB:</label>@item.Dob</p>
            <p><label style="color:limegreen;font-size:18px;"> Status:</label>@item.Status</p>
            <p><label style="color:limegreen;font-size:18px;">Phone:</label>@item.Phone</p>

        }


    </div>

C300/Views/Emsuser/Index.cshtml
@using C300.Models
@model List<Emsuser>
@{
    ViewData["Title"] = "ViewUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.material.min.css" />
<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script>



@*<script src="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"></script>*@
<link rel="stylesheet" href="style.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link href="~/lib/styles/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/lib/scripts/jquery.dataTables.min.js"></script>
<script src="~/lib/scripts/jquery.dataTables.min.js"></script>

<script>
    function ConfirmDelete() {
        if (confirm("Are you sure you want deactivate?") == false) {
            event.stopPropagation;
            event.preventDefault;
            return false;

        }
    }
    function myFunction() {

        var enter, search, table, tr, td, td2, td3, i;
        enter = document.getElementById("myInput");
        search = enter.value.toUpperCase();
        table = document.getElementById("tableid");
        tr = table.getElementsByTagName("tr");


        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            td2 = tr[i].getElementsByTagName("td")[1];
            td3 = tr[i].getElementsByTagName("td")[2];
            if (td, td2, td3) {
                if (td.innerHTML.toUpperCase().indexOf(search) > -1 | td2.innerHTML.toUpperCase().indexOf(search) > -1 | td3.innerHTML.toUpperCase().indexOf(search) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }

            }
        }
    }


</script>


<style>
    th {
        padding-top: 12px;
        font-size: 18px;
        font-weight: bold;
        padding-bottom: 12px;
        background-color: #46B6E2;
    }

    tr td {
        padding: 10px;
        color: white;
        border-bottom: 1px solid #111;
        border-collapse: collapse;
        font-size: 20px;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2
    }

    input[type=text], .form-control {
        width: 130px;
        -webkit-transition: width 0.4s ease-in-out;
        transition: width 0.4s ease-in-out;
    }

        input[type=text]:focus {
            width: 100%;
        }

    .export-form-btn {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 0, 20px;
        width: 12%;
        height: 5%;
        background-color: #57b846;
        border-radius: 25px;
        font-family: 'Microsoft Sans Serif';
        font-size: 15px;
        color: white;
        line-height: 0;
        text-transform: uppercase;
        transition: all 0.4s;
    }


    h2 {
        font-size: 50px;
        color: darkorange;
        font-weight: 700;
    }

    body {
        background-color: white;
    }


    .file_label {
        display: block;
        margin: 50px auto;
        font-size: 20px;
        font-family: Arial;
        width: 200px;
        height: 40px;
        line-height: 40px;
        background-color: #f39c12;
        color: #FFF;
        text-align: center;
        border: 1px solid #CCC;
        border-radius: 5px;
        transition: all 0.3s ease-in-out
    }

        .file_label:hover {
            background-color: orange;
            color: #ffffff;
        }

    .fa {
        margin-right: 5px
    }
</style>

<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover({
            title: setData,
            html: true,
            placement: 'right'

        });
        function setData(id) {
            var set_data = '';
            var element = $(this);
            var id = element.attr("id");
            $.ajax({
                url: "/Emsuser/EmsuserInfo?id" + id,
                method: "post",
                async: false,
                data: { id: id },
                success: function (data) {
                    set_data = data;

                }

            });
            return set_data;

        }

        $('#tableid').DataTable({
            searching: false,
            columnDefs: [
                {

                    targets: [0, 1, 2],
                    className: 'mdl-data-table__cell--non-numeric'

                }
            ]
        });


    });
</script>
<span style="color:red">@TempData["Msg"]</span><br />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <h4><b>Export Format:</b></h4>
    <div>
        <input id="XLSX" name="SelectedFormat" type="radio" checked value="XLSX" />
        <label for="XLSX"><b>XLSX</b></label>

        <input id="XLS" name="SelectedFormat" type="radio" value="XLS" />
        <label for="XLS"><b>XLS</b></label>

        <input id="ODS" name="SelectedFormat" type="radio" value="ODS" />
        <label for="ODS"><b>ODS</b></label>

        <input id="CSV" name="SelectedFormat" type="radio" value="CSV" />
        <label for="CSV"><b>CSV</b></label>

        <input id="PDF" name="SelectedFormat" type="radio" value="PDF" />
        <label for="PDF"><b>PDF</b></label>
    </div>

    <button type="submit" class="export-form-btn ">Export</button>


</form>
<a asp-action="AddUser" asp-controller="Emsuser" style="margin-right:6%" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Create User</a>


<u><a asp-action="ViewUsers" asp-controller="Emsuser"><span class="fa fa-user" style="font-size:18px">View Users As Panel</span></a></u>
<br />
<br />

<input type="text" id="myInput" onkeyup="myFunction()" class="form-control" placeholder="Search for Users!..">


<table class="display" style="width:100%" id="tableid">
    <thead>
        <tr class="header">
            <th style=" color:black">Name</th>
            <th style="color:black">UserId</th>
            <th style="color:black">Email</th>
            <th style="color:black">Role</th>
            <th style="color:black">Status</th>
            <th style="color:black">Updated By</th>
            <th style="color:black">Action</th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null)
            {
            @foreach (Emsuser item in Model)
                {

                <tr>
                    <td>
                        <a href="#" data-toggle="popover" data-trigger="hover" id="@item.UserId">@item.Name</a>
                    </td>
                    <td>@item.UserId</td>
                    <td>@item.Email</td>
                    <td>@item.Role</td>
                    @if (item.Status == "Active")
                    {
                        <td style="color:green">@item.Status</td>
                    }
                    else
                    {
                        <td style="color:red">@item.Status</td>
                    }
                    <td>@item.UpdatedBy</td>

                    <td>

                        <a asp-action="Update" asp-controller="Emsuser" asp-route-id="@item.UserId" class="btn btn-success" style="font-weight:bold;font-size:15px;border-radius:12px">Update</a>
                        @if (item.Status == "Active")
                        {
                            <a asp-action="Activate" asp-controller="Emsuser" asp-route-id="@item.UserId" class="btn btn-success disabled" style="font-weight:bold;font-size:15px;border-radius:12px">Activate</a>
                        }
                        else
                        {
                            <a asp-action="Activate" asp-controller="Emsuser" asp-route-id="@item.UserId" class="btn btn-success" style="font-weight:bold;font-size:15px;border-radius:12px">Activate</a>
                        }


                        <a asp-action="Deactivate" asp-controller="Emsuser" onclick="return ConfirmDelete()" asp-route-id="@item.UserId" class="btn btn-danger" style="font-weight:bold;font-size:15px;border-radius:12px">Deactivate</a>

                    </td>
                </tr>
            }
        }
    </tbody>
</table>





<br />
<br />

@using (Html.BeginForm("UploadCsv", "Emsuser", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="input_file" style="float:left;margin-top:-5%">
        <label for="attachmentcsv" class="file_label" style="color:black;"><i class="fa fa-upload" aria-hidden="true"></i>Import CSV</label>

        <input type="file" style="display:none" name="attachmentcsv" id="attachmentcsv">

    </div>
    <button type="submit" style="margin-left:5%;margin-top:-1%" class="btn btn-primary">Upload</button>
}

C300/Views/Emsuser/Status.cshtml
@{
    ViewData["Title"] = "Status";

    var result = ViewData["MSG"];
    var result2 = ViewData["MSG2"];
    var result3 = ViewData["MSG3"];
    var result4 = ViewData["MSG4"];
    var result5 = ViewData["Temp"] + " , " + ViewData["Humd"] + " , " + ViewData["Light"] + " , " + ViewData["Weight"];

    var display = "";
    int id = (int)ViewData["id"];
    if (id == 1)
    {
        display = result as string;

    }
    else if (id == 2)
    {

        display = result2 as string;
    }
    else if (id == 3)
    {

        display = result3 as string;
    }
    else if (id == 4)
    {
        display = result4 as string;

    }
    else if (id == 5)
    {
        display = result5 as string;

    }
}
@*}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">*@
<link rel="stylesheet" href="~/lib/styles/statusStyle.css" />


<script>
    $(document).ready(function () {
        $("#temp").click(function () {
                console.log("click");
                ajaxCheck();
            });
        $("#humd").click(function () {
                console.log("click");
                ajaxCheck2();
            });
        $("#light").click(function () {
                console.log("click");
                ajaxCheck3();
            });
        $("#weight").click(function () {
                console.log("click");
                ajaxCheck4();
            });
            function ajaxCheck() {
                var ajaxUrl = "http://api.thingspeak.com/channels/541487/feed.json?key=J25VZR7MUMM8RJ4O&location=false";
            $.getJSON(ajaxUrl, function (result) {
                    var last = result.feeds[result.feeds.length - 1];
                    console.log(last);
                    var datetime = last.created_at;
                    datelist = datetime.split("T")
                time = datelist[1].split("Z")
                $.getJSON(
                    "/api/sql/checkstatus/" + datetime + "/" + last.field1,
                    function (data) {
                        if (data == "0") {
                            $("#status").html("Temperature Sensor is Inactive")
                        }
                        else {
                            $("#status").html("Temperature Sensor is active")

                        }
                    }
                );




        });
    }
    function ajaxCheck2() {
        var ajaxUrl = "http://api.thingspeak.com/channels/541487/feed.json?key=J25VZR7MUMM8RJ4O&location=false";
            $.getJSON(ajaxUrl, function (result) {
            var last = result.feeds[result.feeds.length - 1];
            console.log(last);
            var datetime = last.created_at;
            datelist = datetime.split("T")
                time = datelist[1].split("Z")
                $.getJSON(
                    "/api/sql/checkstatus2/" + datetime+"/" + last.field3,
                    function (data) {
                if (data == "0") {
                            $("#status").html(" Humidity Sensor is Inactive")
                        }
                else {
                            $("#status").html("humidity Sensor is active")

                        }
            }
                );




        });
    }
    function ajaxCheck3() {
        var ajaxUrl = "http://api.thingspeak.com/channels/541487/feed.json?key=J25VZR7MUMM8RJ4O&location=false";
            $.getJSON(ajaxUrl, function (result) {
            var last = result.feeds[result.feeds.length - 1];
            console.log(last.field2);
            var datetime = last.created_at;
            datelist = datetime.split("T")
                time = datelist[1].split("Z")
                $.getJSON(
                    "/api/sql/checkstatus3/" + datetime + "/" + last.field2,
                    function (data) {
                if (data == "0") {
                            $("#status").html("Light Sensor is Inactive")
                        }
                else {
                            $("#status").html("Light Sensor is active")

                        }
            }
                );




        });
    }
    function ajaxCheck4() {
        var ajaxUrl = "http://api.thingspeak.com/channels/541487/feed.json?key=J25VZR7MUMM8RJ4O&location=false";
            $.getJSON(ajaxUrl, function (result) {
            var last = result.feeds[result.feeds.length - 1];
            console.log(last);
            var datetime = last.created_at;
            datelist = datetime.split("T")
                time = datelist[1].split("Z")
                $.getJSON(
                    "/api/sql/checkstatus4/" + datetime + "/" + last.field4,
                    function (data) {
                if (data == "0") {
                            $("#status").html(" weight Sensor is Inactive")
                        }
                else {
                            $("#status").html("weight Sensor is active")

                        }
            }
                );




        });
    }
});
</script>
<style>
    #status {
        position: relative;
    }

    .w3-panel p {
        font-size: 25px;
    }

    .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
    }


        .closebtn:hover {
            color: black;
        }
</style>

<h1 style="font-size:40px"><b>Arduino Uno Status</b></h1>
<hr />
<p style="font-size:20px;">
    View the status  of the Arduino Microcontroller here-
</p>
<div class="w3-panel w3-green w3-round">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
    <h2>Info</h2>
    <p id="status"></p>
</div>
<br />
<div class="form-horizontal">

    <img src="~/images/arduino.png" style="height:40%;width:30%;margin-left:55%" />

    <div id="status" style="margin-top:-25%">

        <h3><b>Temperature port status</b></h3>
        @*<a asp-action="Status" asp-controller="Emsuser" asp-route-id="1" class="btn btn-default btn-group-xs" style="background-color:royalblue;color:white;font-weight:bold">Show Status</a>*@
        <button class="btn btn-default btn-group-xs" id="temp" style="background-color:royalblue;color:white;font-weight:bold">Temperature</button>
        <br />
        <br />
        <h3><b>Humidity  port status</b></h3>
        @*<a asp-action="Status" asp-controller="Emsuser" asp-route-id="2" class="btn btn-default btn-group-xs" style="background-color:royalblue;color:white;font-weight:bold">Show Status</a>*@
        <button class="btn btn-default btn-group-xs" id="humd" style="background-color:royalblue;color:white;font-weight:bold">Humidity</button>
        <br />
        <br />
        <h3><b>Light port status</b></h3>
        @*<a asp-action="Status" asp-controller="Emsuser" asp-route-id="3" class="btn btn-default btn-group-xs" style="background-color:royalblue;color:white;font-weight:bold">Show Status</a>*@
        <button class="btn btn-default btn-group-xs" id="light" style="background-color:royalblue;color:white;font-weight:bold">Light</button>
        <br />
        <br />
        <h3><b>Weight port status</b></h3>
        @*<a asp-action="Status" asp-controller="Emsuser" asp-route-id="4" class="btn btn-default btn-group-xs" style="background-color:royalblue;color:white;font-weight:bold">Show Status</a>*@
        <button class="btn btn-default btn-group-xs" id="weight"  style="background-color:royalblue;color:white;font-weight:bold">Weight</button>
        <br />
        <br />

    </div>
</div>

C300/Views/Emsuser/ViewUsers.cshtml
@model List<Emsuser>
@{
    ViewData["Title"] = "ViewUsers";
}
<style>
    b {
        font-weight: bold;
        font-size: 13px;
    }

    .button {
        border: none;
        outline: 0;
        display: inline-block;
        padding: 8px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 15%;
        margin-top: 5px;
        font-size: 13px;
    }


    button:hover, a:hover {
        opacity: 0.7;
    }
</style>


<hr />
<div class="row">
    @if (Model != null)
    {
        @foreach (Emsuser user in Model)
        {
            <div class="col-sm-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a asp-action="Update" style="font-size:20px" asp-controller="Emsuser">
                            @user.Name
                        </a>
                    </div>
                    <div class="panel-body " style="margin:auto;">
                        @{
                            var image = "data:image/png;base64," + user.Picture;
                        }
                        <img id="photo" src="@image" alt="@user.Picture" style="height:80px;width:80px" />
                        <br />
                        <b>User ID:@user.UserId</b>
                        <br />
                        <b>Email:@user.Email</b>
                        <br />
                        <b>Status:@user.Status</b>
                        <br />
                        <b>Role:@user.Role</b>
                        <br />
                        <a asp-action="Update" asp-route-id="@user.UserId" class="btn btn-success" style="font-weight:bold;font-size:15px;border-radius:12px" asp-controller="Emsuser">Update</a>
                        <a asp-action="Deactivate" asp-route-id="@user.UserId" class="btn btn-danger" style="font-weight:bold;font-size:15px;border-radius:12px" asp-controller="Emsuser">Deactivate</a>


                    </div>
                </div>
            </div>

                            }


                            }



</div>